### ISSUE TITLE
mod the spire doesnt work at all

### ISSUE THREAD

**Issue by Downanddirty4568** [kiooeht/ModTheSpire#87] opened 2018-09-04 15:06 UTC
![errormessage1](https://user-images.githubusercontent.com/38453823/45039716-089d5600-b019-11e8-9860-b21ca7eb93df.jpg)
![untitled](https://user-images.githubusercontent.com/38453823/45039730-0f2bcd80-b019-11e8-82fb-dc3444a62f17.jpg)
ever since the update that is titled "the one that breaks everything" it has done exactly that although i don't know if its a problem with modthespire or a problem with base mod but basically i have continuously downloaded the latest of the latest versions of every single mod i have and that is what keeps breaking it so im hoping u can help im gonna post this same thing under the base mod creator just in case its a problem with the base mod

**Comment by kiooeht** [comment] 2018-09-04 19:34
Closed as duplicate of https://github.com/daviscook477/BaseMod/issues/123 and I commented there.

**Closed by kiooeht** 2018-09-04 19:34 UTC
